In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_excel("Arsenal_Data (1).xlsx")

In [3]:
print(df.columns)

Index(['Year', 'Match_Played', 'Points', 'Point_Gap', 'GS_ARS', 'GC_ARS',
       'Wins', 'GS_1', 'GC_1', 'WvT5', 'DvT5', 'LvT5', 'TD_ARS', 'TL_ARS',
       'TD_1', 'PD_1_19', 'PD_2_19', 'Clean_sheet_1_19', 'Clean_sheet_2_19',
       'Injury', 'ATT_Injury', 'Mid_Injury', 'Def_injury'],
      dtype='object')

In [4]:
#KPIs
df["Goal_difference"] = df['GS_ARS']-df['GC_ARS']
df["Points_per_game"] = df['Points'] / df['Match_Played']
df["Win Percentage"] = df["Wins"] / df['Match_Played']
df["Draw Percentage"] = df["TD_ARS"] / df['Match_Played']
df["Loss Percentage"]  = df["TL_ARS"] / df['Match_Played']

In [19]:
df.to_excel('arsenal_processed1.xlsx', index=False)

In [6]:
print(df[['Year', 'Points_per_game', 'Win Percentage', 'Draw Percentage', 'Loss Percentage']])

      Year  Points_per_game  Win Percentage  Draw Percentage  Loss Percentage
0  2024-25            1.947           0.526            0.368            0.105
1  2023-24            2.342           0.737            0.132            0.132
2  2022-23            2.211           0.684            0.132            0.158

# Insight 1:
From the season 22-23 to the season 24-25, Arsenal's point/points per game ration was inconsitent. Over the course of these 3 years, their loss percentage remain consistent, but the draw percentage in 24-25 season was more than double the amount compared to the other two seasons, causing them the title.

In [10]:
#about the current season:
data2=pd.read_excel('Current Season (1).xlsx')
print(data2.columns)

Index(['points_ARS', 'points_MC', 'Match_played_ARS', 'Match_played_MC',
       'TGS_ARS', 'TGS_MC', 'TGC_ARS', 'TGC_MC', 'TW_ARS', 'TW_MC', 'TD_ARS',
       'TD_MC'],
      dtype='object')

In [18]:
#KPI comparison for this season
data2['Points_per_game']=data2['points_ARS'] / data2['Match_played_ARS']
data2['Win %']= data2['TW_ARS'] / data2['Match_played_ARS']
data2['Draw %'] = data2['TD_ARS'] / data2['Match_played_ARS']
print("KPI this Season (Arsenal): ")
print(data2[['Points_per_game', 'Win %', 'Draw %']])

data2['Points_per_game_MC']=data2['points_MC'] / data2['Match_played_MC']
data2['Win % MC']= data2['TW_MC'] / data2['Match_played_MC']
data2['Draw % MC'] = data2['TD_MC'] / data2['Match_played_MC']
print("KPI this Season (ManCity): ")
print(data2[['Points_per_game_MC', 'Win % MC', 'Draw % MC']])

KPI this Season (Arsenal):
   Points_per_game     Win %    Draw %
0         2.258065  0.677419  0.225806
KPI this Season (ManCity):
   Points_per_game_MC  Win % MC  Draw % MC
0            2.033333       0.6   0.233333

# Insight 2: 
Arsenal's points per game in this current season has improved, and much better than their previous 3 seasons. Although there's still a good point gap from second position mancity, Arsenal's draw percentage is still alarming. Arsenal's draw percentage although came out better than the immediate prebious season, but still worse than 23-24 and 22-23 season. 

On the other hand, second position holder Mancity also has similar pattern of draw percentage

# Question at this phase: 
Are draws causing more harms than straight losses? Do epl demands more attacking football in the recent years? We can get to know about that by analysing the performance of the champoins in last 3 seasons

In [20]:
#about the current season:
data3=pd.read_excel('Champ_Dataset.xlsx')
print(data3.columns)

Index(['Year', 'Match_played', 'points', 'Win', 'Draw', 'Loss'], dtype='object')

In [22]:
# Calculate additional metrics
data3['Points_per_Game'] = data3['points'] / data3['Match_played']
data3['Draw_Percentage'] = (data3['Draw'] / data3['Match_played'])
data3['Loss_Percentage'] = (data3['Loss'] / data3['Match_played'])

table = data3[['Year', 'Points_per_Game', 'Draw_Percentage', 'Loss_Percentage']]

table = table.round(2)
table

      Year  Points_per_Game  Draw_Percentage  Loss_Percentage
0  2024-25             2.21             0.24             0.11
1  2023-24             2.39             0.18             0.08
2  2022-23             2.34             0.13             0.13

# Insight 3:
Arsenal's point per game ratio for this season (2.25) is better than the last 3 champions of the prem. They got better chances of winning compared to their last 3 seasons.

# Insight 4:
Arsenal's draw percentage in 2022-23 season was similar to the champions of that season. (point gap between the champions and Arsenal was 5 points). For season 2023-24, Arsenal had better draw percentages than the champions (0.13 vs 0.18), and the point gap was 2 points which was better than it's previous season. 

# Insight 5: 
Arsenal's draw percentage in 2024-25 season (0.36), was significantly higher than the champions in that season (0.24). And the point gap between Arsenal an the champions was 10 points

# Analytical result of insight 3,4 and 5:
The more draw ratio Arsenal had comapred to the league leaders, the bigger the point gap between the champions and Arsenal was vsisble for most of the seasons in my sample

In [23]:
data3.to_excel('champions_processed.xlsx', index=False)

In [26]:
#Total points lost for arsenal: A comparison
df['points_dropped_from_draws']=df['TD_ARS']*2
df['points_dropped_from_loss']=df['TL_ARS']*3

df[["Year", "points_dropped_from_loss", "points_dropped_from_draws"]]

      Year  points_dropped_from_loss  points_dropped_from_draws
0  2024-25                        12                         28
1  2023-24                        15                         10
2  2022-23                        18                         10

# Insight 6:
Arsenal lost 18 extra points due to draws compared to 2023–24. Even converting half (9 points) would reduce the title gap significantly.

# Diagnosis:
Let's try to discover the main reason behind their inconsitency

In [27]:
df[['Year', 'GS_ARS', 'GC_ARS', 'Goal_difference']]

      Year  GS_ARS  GC_ARS  Goal_difference
0  2024-25      69      34               35
1  2023-24      91      29               62
2  2022-23      88      43               45

# insight 7: 
Arsenal's goal conversion rate was at their best in 2023-24 season. Conceeded the least and scored the most. Their diffensive errors from 2022-23 was well recovered, and was significantly close in 23-24 and 24-25 seasons. However, their goal socring record was a lot down at the 2024-25 season (at least 18 goals less), where they had the most draws as well. 
Appearntly making them go big for an attacker this season. 

This isnight justfies their spenidng on Viktor Gyokores was well justified

In [31]:
df[['Year', 'Points', 'Injury', 'GS_ARS', 'GC_ARS', 'ATT_Injury', 'Mid_Injury', 'Def_injury']]

      Year  Points  Injury  GS_ARS  GC_ARS  ATT_Injury  Mid_Injury  Def_injury
0  2024-25      74      11      69      34           3           3           5
1  2023-24      89       6      91      29           2           2           2
2  2022-23      84       7      88      43           2           2           3

# Insight 8:
Arsenal's defence seems to be the less of a problem than their creative players and goal scorers. In 22-23 season, they had way less injury for defenders compared to the 24-25 season, but conceeded way more goals in 22-23 season. 

# Insight 9: 
Arsenal had most their injuries, most less points, worst goal scoring record in 24-25 season, due to the most number of attacking players being injured in overall comparison. 

# analytical result:
Defence of Arsenal proves to have solid back up options, rather than injuries it was their performance in different seasons that impacted in a different way. But their attacking options seems to be more dependent on the first team players only.

In [33]:
df[["Year", 'PD_1_19', 'PD_2_19']]

      Year  PD_1_19  PD_2_19
0  2024-25       12       10
1  2023-24       15        9
2  2022-23       10       18

In [35]:
df[['Year', 'Clean_sheet_1_19', 'Clean_sheet_2_19']]

      Year  Clean_sheet_1_19  Clean_sheet_2_19
0  2024-25                 8                 9
1  2023-24                 6                12
2  2022-23                 7                 7

# Insight 10:
Arsenal's clean sheet records at the first half of the season and the second half of the season was similar for the 22-23 season (having equal number of clean sheets), it skewed in 23-24 season, and was almost similar in 24-25 season. meaning Arsenal still control games — but fail to capitalize on that control.

# Core Diagnosis: 
Arsenal are not losing more games; they are failing to win controlled games.

In [37]:
df['goals_per_game']=df['GS_ARS']/38
df[["Year", "goals_per_game", "TD_ARS"]]

      Year  goals_per_game  TD_ARS
0  2024-25        1.815789      14
1  2023-24        2.394737       5
2  2022-23        2.315789       5

# Insight 11: 
A drop of 0.57 goals per game (~24%) directly correlates with a +9 draw increase, proving that reduced attacking output leads to inability to convert matches.

# Final Diagnostic Statement: 
Arsenal’s inconsistency is caused by a quantifiable drop in attacking output (−24%) combined with increased defensive instability (+150% defensive injuries), resulting in a +180% increase in draws, which directly reduces points.

In [38]:
df.to_excel('arsenal_processed2.xlsx', index=False)